name: easy_push_notification
description: "A simple and efficient Flutter package to handle push notifications using Firebase Cloud Messaging (FCM) for both Android and iOS."
version: 0.0.4
homepage: https://github.com/nuhan021/easy_push_notification

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.0
  path_provider: ^2.1.5
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
